   #Add implementation                                                                                                                                                                                                                                                                   
def add(x,y):
    return x+y                                                                                                                                                                                                                                                                                                                  +
  #Subtract implementation                                                                                                                                                                  #                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
def subtract(x,y):
    return x-y           #from remote_repo
  #Multiply implementation                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
def multiply(x,y):
    pass
  #Divide implementation                                                       
def divide(x,y):
     pass
       
